### PR TITLE
Support for NS7 / Angular 10

### PR DESCRIPTION
**Pull request by cvietor**
- Updated nativescript and angular dependencies (supporting ns7 and angular10)

### CODE REVIEW

**Comment by danvick** [comment]
Thanks for your contribution @cvietor. You're the best

**Comment by cvietor** [comment]
@danvick can you release a new version on npm? Since it's a breaking change, a major version jump to 3.0.0 would be good :-)

**Comment by cvietor** [comment]
@danvick Any ETA on a new release on npm?

**Comment by danvick** [comment]
Done. Thanks for your patience.

**Pull request merged**
